# based anaconda 4.2 and install tf keras pymongo spark
FROM continuumio/anaconda3:4.2.0
#RUN apt-get update --fix-missing &&
#RUN apt-get install -y build-essential libssl-dev
RUN pip install  pyspark tensorflow-gpu
